version: "2"
services:
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: biwed_lab_clickhouse
    restart: "no"
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"